authapp/urls.py
from django.urls import path

from django.urls import path

from authapp import views


app_name = "authapp"
urlpatterns = [
    path('signup/', views.signup, name= 'account_signup'),
    path("login/", views.loginUser, name="account_login"),
    path("logout/", views.logoutUser, name="account_logout"),
   	path('changepassword/', views.PasswordChange, name='change_password'),
   	path('changepassword/done', views.PasswordChangeDone, name='change_password_done'),

]

mypost/urls.py
from django.urls import path

from . import views

from .views import (
    SearchView,
    CommentListView,
    HomeView,
    CreatePostView,
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
)

app_name = 'mypost'
urlpatterns = [
    path('', HomeView.as_view(), name ='home'),
    path('post-create/', CreatePostView.as_view(), name='post_create'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('post-update/<int:pk>/',PostUpdateView.as_view(), name='post_update' ),
    path('post-detail/<int:pk>/', PostDetailView.as_view(), name ='post_detail'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name ='post_delete'),

    # path('post-detail/<int:pk>/comment/', CommentView.as_view(), name='comment_post' ),
    path('post-detail/<int:pk>/comment-list/', CommentListView.as_view(), name='comment_post' ),
    path('search/', SearchView.as_view(), name='search_post' ),
    
    # path('search/', views.search, name='search_post'),


    
]

post/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authapp.urls')),
    path('', include('mypost.urls')),
    path('profile/', include('profilapp.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

profilapp/urls.py
from django.urls import path

from profilapp.views import (
    profil,
    # ProfileCreateView,
    ProfileUpdateView,
    ProfileDetailView,
)


app_name = 'profilapp'
urlpatterns = [
    # path('create/', ProfileCreateView.as_view(), name='create_profile'),
    
    path('update/<pk>/', ProfileUpdateView.as_view(), name='update_profile'),
    path('<pk>/', ProfileDetailView.as_view(), name="profile"),
    
]

profilapp/models.py
from django.db import models

# Create your models here.
import uuid
from django.db import models
from django.urls import reverse
from PIL import Image
from django.conf import settings
from django.db.models.signals import post_save

import os

from utils.models import UrlMixin, TimeStampedModel

User = settings.AUTH_USER_MODEL

# Create your models here.
def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    profile_pic_name = 'user_{0}/profile.jpg'.format(instance.user.id)
    full_path = os.path.join(settings.MEDIA_ROOT, profile_pic_name)

    if os.path.exists(full_path):
    	os.remove(full_path)

    return profile_pic_name  




# SEXE = (
#     ('M', 'masculin'),
#     ('F','Feminin')
# )

# CONTINENT = (
#     ('AF','AFRIQUE'),
#     ('UE', 'EUROPE'),
#     ('AM', 'AMERIQUE'),
#     ('AS', 'ASIE'),
#     ('OC','OCEANIE'),
# )

class TimeStampedModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now =True)

    class Meta:
        abstract = True

# class profilMixin(models.Model):
#     id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
#     user = models.OneToOneField(User, verbose_name="Auteur", on_delete=models.CASCADE)
#     name = models.CharField( max_length=20 , verbose_name = 'Nom de profil')
#     email = models.EmailField(max_length=254, verbose_name = ' E-mail')

#     class Meta:
#         abstract = True


# Create your models here.
class Profile(TimeStampedModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,unique=True, null = False, editable=False)
    email = models.EmailField(max_length=254, verbose_name = ' E-mail')
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    proffession = models.CharField(max_length=50)
    tel = models.IntegerField(null = True, blank = True, verbose_name = 'Numero de Téléphone')
    location = models.CharField(max_length=50, null=True, blank=True)
    url = models.URLField(max_length=200, null=True, blank=True)
    profile_info = models.TextField(max_length=150, null=True, blank=True)
    picture = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name='Picture')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        SIZE = 250, 250

        if self.picture:
            pic = Image.open(self.picture.path)
            pic.thumbnail(SIZE, Image.LANCZOS)
            pic.save(self.picture.path)

    def __str__(self):
        return self.user.username

    def get_profil_url(self):
            return reverse('profilapp:profile', kwargs = {
                'pk': self.id
            })


# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

# post_save.connect(create_user_profile, sender=User)
# post_save.connect(save_user_profile, sender=User)





# class AuthorProfil(profilMixin, TimeStampedModel):
#     tel = models.IntegerField(verbose_name = 'Numero de Téléphone')
#     sexe = models.CharField(choices = SEXE, max_length = 1)
#     proffession = models.CharField(max_length=50)
#     experience = models.IntegerField(verbose_name = 'Année d\'experince')
#     pays = models.CharField(max_length=30)
#     continent = models.CharField(choices = CONTINENT, max_length=50)
#     profil_picture = models.ImageField(upload_to='AuthorPicture',max_length=1200, verbose_name = 'photo de profile', null = True, blank = True)

#     def __str__(self):
#         return self.name

#     def get_profil_url(self):
#             return reverse('profilapp:profil', kwargs = {
#                 'uuid': self.id
#             })

# class ReaderProfil(profilMixin, TimeStampedModel):
#     profil_picture = models.ImageField(upload_to='ReaderPicture',max_length=1200, verbose_name = 'photo de profile', null = True, blank = True)

#     def __str__(self):
#             return self.name

#     def get_profil_url(self):
#             return reverse('profilapp:profil', kwargs = {
#                 'uuid': self.id
#             })

profilapp/forms.py
from django import forms
from .models import Profile


class EditProfileForm(forms.ModelForm):
	picture = forms.ImageField(required=False)
    
	first_name = forms.CharField(widget=forms.TextInput(
        attrs={
                 'class': 'form-control'}
                 )
            , max_length=50, required=False)

	last_name = forms.CharField(widget=forms.TextInput(
        attrs={
                 'class': 'form-control'
            })
            , max_length=50, required=False)

	location = forms.CharField(widget=forms.TextInput(
        attrs={
                 'class': 'form-control'
            })
            , max_length=25, required=False)

	url = forms.URLField(widget=forms.TextInput(
        attrs={
                 'class': 'form-control'
            })
            , max_length=60, required=False)

	profile_info = forms.CharField(widget=forms.Textarea(
        attrs={
                 'class': 'form-control'
            })
    , max_length=260, required=False)

	class Meta:
		model = Profile
		fields = ('picture', 'first_name', 'last_name', 'location', 'url', 'profile_info')

profilapp/views.py
from django.shortcuts import render, redirect, reverse
# from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.base import TemplateView

from mypost.models import Post

from profilapp.models import Profile
from profilapp.forms import EditProfileForm

# Create your views here.

# @login_required
def profil(request, uuid):
    ReaderProfil = Profile.objects.get(id = uuid)
    return render(request, 'profilapp/profil.html', {'ReaderProfil': ReaderProfil})


def profilpage(request):
    return render(request, 'profilapp/profile.html',)


# class ProfileCreateView(CreateView):
#     model = Profile
#     template_name = "profilapp/edit_profile.html"
#     form_class = EditProfileForm
#     # fields = ['first_name', 'last_name', 'location', 'url','profile_info','picture']

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["title"] = 'Create Profile'
#         return context

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         form.save()
#         return redirect(reverse('mypost:home'))


class ProfileUpdateView(UpdateView):
    model = Profile
    template_name = "profilapp/edit_profile.html"
    form_class = EditProfileForm
    # fields = ['first_name', 'last_name', 'location', 'url','profile_info','picture']

    def get_context_data(self, **kwargs):
        user = self.request.user.id
        profile = Profile.objects.get(user__id=user)
        context = super().get_context_data(**kwargs)
        context["title"] = 'Update Profile'
        context['user'] = user
        context['profile'] = profile
        return context

    def form_valid(self, form):
        user_id = self.request.user.id
        profile = Profile.objects.get(user__id=user_id)
        form.instance.user = self.request.user
        form.save()
        return redirect(reverse('profilapp:profile', kwargs = {'pk': profile.id}))


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "profilapp/profil.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'last_view' in self.request.session:
            last_post_view = Post.objects.all().\
                filter(id = self.request.session["last_view"])
            context['last_post_view'] = last_post_view
        return context
    

    

profilapp/templates/profilapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'mypost/_head.html' %}
 <body class="body">
     
     {% block body %}

        
        {% comment %}
        {% if messages %}
        <div>
        <strong>Messages:</strong>
        <ul>
            {% for message in messages %}
            <li>{{message}}</li>
            {% endfor %}
        </ul>
        </div>
        {% endif %}
        {% endcomment %}
    
        {% block content %}
        
        {% endblock %}

    {% endblock %}

    {% block extra_body %}
    
    {% endblock %}

    {% include 'mypost/_footer.html' %}

    
    {% block script %}
    
    {% endblock script %}

  </body>
</html>

profilapp/templates/profilapp/edit_profile.html
{% extends 'profilapp/base.html' %}
{% load static %}

        
{% block content %}


<div class="container px-lg-5">
  <div class="container pt-5 w-lg-75 bg-dark shadow rounded ">

    <form class="text-light fs-5 pb-1" method="post" enctype="multipart/form-data" action="" role="form">
      {% csrf_token %}
    <h3 class="title is-3 text-center">Edit Profile</h3>
    <div class="container w-lg-85 form-modif">

      
      <div class=" field lead mx-4">
        <label class=" m-md-2 label is-medium">Choose your picture</label>
              <div class="file is-boxed">
                {{ form.picture }}
              </div>
          </div>

          <div class="field lead m-4">
              <label class="label is-medium">First name</label>
              <div class="control">
                {{ form.first_name }}
              </div>
          </div>

          <div class="field lead m-4">
              <label class="label is-medium">Last name</label>
              <div class="control">
                {{ form.last_name }}
              </div>
          </div>

          <div class="field lead m-4">
              <label class="label is-medium">Location</label>
              <div class="control">
                {{ form.location }}
              </div>
          </div>

          <div class="field lead m-4">
            <label class="label is-medium">url</label>
            <div class="control">
              {{ form.url }}
              </div>
          </div>

          <div class="field lead m-4">
              <label class="label is-medium">BIO</label>
              <div class="control">
                {{ form.profile_info }}
              </div>
          </div>

          <div class="row lead m-4">
            <div class="col s12">
              <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
            </div>
          </div>


          <div class="field lead m-4">
          <p class="control">
            <button type="submit" value="login" class="btn btn-outline-info">
              Update
            </button>

            
            </p>
          </div>

        </div>
        </form>

  </div>
</div>

{% endblock %}

profilapp/templates/profilapp/profil.html
{% extends 'mypost/base.html' %}
{% load static %}

{% block content %}

<main class="">

    <section class="row translate-y">
        
        <div class="col-md-3 pb-2 py-lg-5">
            {% if user.is_authenticated and user == profile.user %}
            <div class="mx-0 p-4">
                <h4 class="text-center pt-lg-4">Actions principales</h4>
                <a class="btn btn-outline-info m-1 " href="{% url 'mypost:post_create' %}">Create un post</a>
                <a class="btn btn-outline-info m-1 " href="{% url 'profilapp:update_profile' profile.id %}">Update Profil</a>
                <a class="btn btn-outline-info m-1" href="{% url 'authapp:change_password' %}">Change pssword</a>
                
            {% endif %}
                    

            </div>
        </div>

    <div class="rounded shadow  col-md-6 bg-dark text-light lead py-lg-3">
        <div class="container pb-3 ">
            <figure class="image pt-5 mt-5 d-block m-auto w-50">
                {% if profile.picture %}
                <a href="{{profile.picture.url}}">
                    <img class="img-fluid rounded rounded-3 rounded-circle" src="{{ profile.picture.url }}">
                </a>
                {% else %}
                <a href="{% static 'profilapp/images/pigeon.jpg' %}">
                    <img class="img-fluid rounded rounded-pill " src="{% static 'profilapp/images/pigeon.jpg' %}" alt="" class="img-fluid">
                </a>
                    {% if user.is_authenticated and user == profile.user %}
                        <p class="text-center pt-3">Photo de profil par defaut. Veuiller changez si vous le voullez!</p>
                    {% endif %}
                {% endif %}
            </figure>

            <div class="content text-center p-3">
                <h1 class="d-inline">
                    {% if profile.first_name %}
                    {{ profile.first_name }} {{ profile.last_name }}
                     {% endif %}
                </h1>
                <h2 class="fw-lighter pt-3">Tags:@{{profile.user}}</h2>
            </div>
            
            <div class="container text-light">
                <h4 class="text-center pt-5">Informations importantes</h4>
                
                <p class="text-center"><span class="fw-lighter
                    ">Join</span> {{profile.created}}</p>
                
                {% if profile.proffession is not None %}
                    
                <p class="text-center"><span class="fw-lighter
                    ">Proffesion: </span>{{profile.proffession}}</p>
                {% else %}
                
                {% endif %}

                {% if profile.experience is not None %}
                    
                <p class=" pt-3"><span class="fw-lighter 
                    ">Année d'expérience:</span> {{profile.experience}}</p>
                {% else %}
                
                {% endif %}

                {% if profile.first_name is not None %}
                    
                <h4 class=" pt-3 text-center"><span class="fw-lighter  
                    ">En savoir plus sur </span> {{profile.first_name}}</h4>
                {% else %}
                
                {% endif %}
                
                    
                {% if profile.tel is not None %}
                <p class=" pt-3"> <span class="fw-lighter 
                    ">Téléphone:</span> 
                    {{profile.tel}}</p>
                {% else %}
                {% endif %}
                        
                
                
                {% if profile.email is not None %}
                    
                <p class=" pt-3"> <span class="fw-lighter 
                    ">E-mail:</span> <a class="text-light px-2" href="mailto:{{profile.email}}">{{profile.email}}</a>
                </p>
                <p class=" pt-3"><a class="d-block text-light text-decoration-none" href="">Mail me</a>
                </p>

                {% else %}
                {% endif %}
                    
                
                
                {% if profile.location is not None %}
                <p class=" pt-3"> <span class="fw-lighter 
                    ">Localisation:</span> 
                     {{profile.location}}
                </p>
                {% else %}
                {% endif %}
                    
                
                <!--  travailler avec len pour trouver la taille de url et de bio -->
                {% if profile.url is not None %}
                    
                <p class=" pt-3"> <span class="fw-lighter 
                    ">Site web: <a class="text-light" href="{{profile.url}}" target="_blank">{{profile.url}}</a> </p>
                {% else %}
                {% endif %}
                    
                {% if profile.profile_info is not  None %}
                
                <p class=" pt-3"> <span class="fw-lighter
                    ">Bio:</span> 
                     {{profile.profile_info}}</p>
                {% else %}
                
                {% endif %}

            </div>
        </div>
    </div>

    <div class=" col-md-3 py-lg-5 ">
        <div class="container">
            <h4 class="text-center">Statistiques</h4>
            <h3>Post lu récément</h3>
            
            {% if last_post_view %}
            
                {% for last_post in last_post_view %}
                    <a class="text-decoration-underline" href="{{last_post.get_absolute_url}}">{{last_post.title}}</a>
                    <p>{{last_post.content| truncatewords:"50"}}</p>
                    <p>by<span class="lead"> {{last_post.post_by}}</span> depuis <span> {{last_post.created}}</span></p>
                {% endfor %}
                    
            {% endif %}
                
            

                
        </div>
    </div>

</section>


    {% comment %}

    {% if user.is_authenticated and user != profile.user %}
        <div class="media-right">
        {% if follow_status == True %}
        <a href="{% url 'follow' profile.user 0 %}" class="button is-danger">Unfollow</a>
        {% else %}
        <a href="{% url 'follow' profile.user 1 %}" class="button is-success">Follow</a>
        {% endif  %}
    </div>
    {% endif %}

    {% endcomment %}
</main>


{% endblock content %}
    