authapp/urls.py
from django.urls import path

from django.urls import path

from authapp import views


app_name = "authapp"
urlpatterns = [
    path('signup/', views.signup, name= 'account_signup'),
    path("login/", views.loginUser, name="account_login"),
    path("logout/", views.logoutUser, name="account_logout"),
   	path('changepassword/', views.PasswordChange, name='change_password'),
   	path('changepassword/done', views.PasswordChangeDone, name='change_password_done'),

]

mypost/urls.py
from django.urls import path

from . import views

from .views import (
    SearchView,
    CommentListView,
    HomeView,
    CreatePostView,
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
)

app_name = 'mypost'
urlpatterns = [
    path('', HomeView.as_view(), name ='home'),
    path('post-create/', CreatePostView.as_view(), name='post_create'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('post-update/<int:pk>/',PostUpdateView.as_view(), name='post_update' ),
    path('post-detail/<int:pk>/', PostDetailView.as_view(), name ='post_detail'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name ='post_delete'),

    # path('post-detail/<int:pk>/comment/', CommentView.as_view(), name='comment_post' ),
    path('post-detail/<int:pk>/comment-list/', CommentListView.as_view(), name='comment_post' ),
    path('search/', SearchView.as_view(), name='search_post' ),
    
    # path('search/', views.search, name='search_post'),


    
]

post/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authapp.urls')),
    path('', include('mypost.urls')),
    path('profile/', include('profilapp.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authapp/models.py
from django.db import models

# Create your models here.

authapp/forms.py
from  django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate

from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(forms.Form):
    username = forms.CharField(
        label = "Nom d'utilisateur",
        widget=forms.TextInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )

    email = forms.EmailField(
        label = "E-mail",
        widget=forms.EmailInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )

    new_password= forms.CharField(
        label = "Mots de passe",
        widget=forms.PasswordInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )


    confirm_password= forms.CharField(
        label = "confirmer le mot depasse",
        widget=forms.PasswordInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username__iexact = username)
        if qs.exists():
            raise forms.ValidationError('This is an invalid username, please pick another!')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email__iexact = email)
        if qs.exists():
            raise forms.ValidationError('This email is already in use! Please pick another')
        return email

    # def clean_password(self):
    #     new_password = self.cleaned_data.get('new_password')
    #     print(new_password)
    #     confirm_password = self.cleaned_data.get('confirm_password')
    #     print(confirm_password)

    #     if new_password != confirm_password:
    #         raise forms.ValidationError('Password don\'t match')

    #     return new_password

class UserLoginForm(forms.Form):
    username = forms.CharField(
        label = "Nom d'utilisateur",
        widget=forms.TextInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )

    new_password = forms.CharField(
        label = "Mots de passe",
        widget=forms.PasswordInput(
            attrs={'required': True,
                 'class': 'form-control'}
        )
    )

    remember = forms.BooleanField(
        required=False,
        label = "Se souvenir de moi"
        )


    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('new_password')
        print(password)
        qs = User.objects.filter(username__iexact = username)
        if not qs.exists():
            print('exist')
            raise forms.ValidationError('User does not exist!')

        if username and password:
            user = authenticate( username = username, password = password)

            if not user:
                print('does not exist')
                raise forms.ValidationError('This user does not exist!')

            if not user.check_password(password):
                print('incorrect password')
                raise forms.ValidationError('Incorrect password')
        return super(UserLoginForm, self).clean(*args, **kwargs)

    

class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(widget=forms.PasswordInput(
                                    attrs={'class': 'input is-medium'}), 
                                    label="Old password", required=True)
    new_password = forms.CharField(widget=forms.PasswordInput(
                                    attrs={'class': 'input is-medium'}), 
                                    label="New password", required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput(
                                    attrs={'class': 'input is-medium'}), 
                                    label="Confirm new password", required=True)

    class Meta:
            model = User
            fields = ('id', 'old_password', 'new_password', 'confirm_password')


    def clean(self):
        super(ChangePasswordForm, self).clean()
        id = self.cleaned_data.get('id')
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] =self.error_class(['Old password do not match.'])
        if new_password != confirm_password:
            self._errors['new_password'] =self.error_class(['Passwords do not match.'])
        return self.cleaned_data

authapp/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login, logout
from django import forms
from django.contrib import messages
from django.contrib.auth import get_user_model

from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from authapp.decorators import unauthenticated_user

User = get_user_model()
from authapp.forms import UserRegisterForm, UserLoginForm, ChangePasswordForm
from profilapp.models import Profile
# Create your views here.

@unauthenticated_user
def signup(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        email = form.cleaned_data.get('email')
        password = form.cleaned_data['new_password']
        try:
            user = User.objects.create_user(username,email, password)
            print('work')
            print(user.password)
        except:
            user = None
            print('don\'t work')

        if user != None:
            print('helloooooo')
            login(request, user)
            profile = Profile.objects.create(user = user, email = email, first_name=username)
            messages.success(request, "Account was created for" " "  + username)
            return redirect(reverse('mypost:home'))
        else:
            form = UserRegisterForm()
    
    context = {
        'form':form
    }
    return render(request, 'authapp/signup.html', context)

@unauthenticated_user
def loginUser(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        new_password = form.cleaned_data['new_password']

        user = authenticate(request, username = username, password = new_password)
        print('hello')
        if user != None:
            print('work')
            login(request, user)
            return redirect(reverse('mypost:home'))

        else:
            prin('salut')
            form = UserLoginForm()
            messages.info(request, "Username OR Password is incorrect")

    context = {
    'form':form
    }
    return render(request, 'authapp/login.html', context)


@login_required
def logoutUser(request):
    username = request.user.username
    if request.method == 'POST':
        logout(request)
        messages.info(request, "You're login out", username)
        return redirect(reverse('authapp:account_login'))
    
    return render(request, 'authapp/snippet.html')


@login_required
def PasswordChange(request):
	user = request.user
	if request.method == 'POST':
		form = ChangePasswordForm(request.POST)
		if form.is_valid():
			new_password = form.cleaned_data.get('new_password')
			user.set_password(new_password)
			user.save()
			update_session_auth_hash(request, user)
			return redirect('change_password_done')
	else:
		form = ChangePasswordForm(instance=user)

	context = {
		'form':form,
	}

	return render(request, 'authapp/change_password.html', context)



def PasswordChangeDone(request):
    messages.info('request', 'Your password has been succesfully changed')
    return HttpResponseRedirect(reverse('authapp:account_login'))
	# return render(request, 'authapp/change_password_done.html')

authapp/templates/authapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'mypost/_head.html' %}
 <body class="body">
     
    {% block body %}

     
    {% comment %}
    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    {% endcomment %}
    
        {% block content %}
        
        {% endblock %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}

    
    {% block script %}
      
    {% endblock script %}

  </body>
</html>

authapp/templates/authapp/change_password.html
{% extends "authapp/base.html" %}
{% load i18n %}

{% load static %}

        
{% block content %}


<div class="container p-5">
  <div class="container w-auto w-lg-75 bg-dark shadow shadow-lg rounded ">

    <h1 class=" pt-5 text-light fw-bold fs-3 text-center ">{% trans "Change password" %}</h1>
    
    <form method="post" action="" role="form" class="col s12 text-light lead pb-5">
      <div class="container  mt-5 text-center ">
        <div class="lead m-3">
          <span style="color: red; font-weight: bold;">{{ form.errors.old_password }}</span>
          <span style="color: red; font-weight: bold;">{{ form.errors.new_password }}</span>
          <span style="color: red; font-weight: bold;">{{ form.errors.confirm_password }}</span>
        </div>

        {% csrf_token %}
        {{ form.id }}
        <div class="lead m-3">
            <label for="old_password" class="px-4">Old password</label>
            {{ form.old_password }}
        </div>


        <div class="lead m-3">
            <label for="new_password" class="px-3">New password</label>
            {{ form.new_password }}
        </div>

        <div class="lead m-3">
            <label for="password" class="px-1">Re-type password</label>
            {{ form.confirm_password }}
        </div>
      <button class="btn btn-outline-info  text-light lead waves-effect waves-light" type="submit" name="action"><Change class="material-icons left">send</Change> Password</button>
    </div>
    </form>
  </div>
</div>

{% endblock %}

authapp/templates/authapp/change_password_done.html
{% extends "authapp/base.html" %}
{% load i18n %}

{% block content %}

<div class=" text-center">
  <div class="col s12 center-align">
    <i class="large material-icons green-text">check_circle</i>
  </div>
  <div class="col s12 center-align">
    <h4>Your password has been succesfully changed</h4>
  </div>
</div>

{% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
{% endif %}

<br />
<br />
{% endblock %}

authapp/templates/authapp/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'authapp/css/auth.css' %}">

    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    
    {% endblock %}

  </head>

authapp/templates/authapp/login.html
{% extends "authapp/base.html" %}


{% load i18n %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<div class="container p-5">

<div class="container rounded w-auto w-lg-75 bg-dark shadow ">

<h1 class=" pt-3 text-light fw-bold fs-3 text-center ">{% trans "Sign In" %}</h1>

<div class=" text-light">
  <div class="container fs-5 text-center">
    {% include 'authapp/messages.html' %}
    {{form.errors}}
  </div>
  <p class="i-account text-center">You don't have an account? Then please <a class = "text-light lead mx-2" href="{% url 'authapp:account_signup' %}">sign up</a></p>
</div>


<form class="login text-light" method="POST" action="">
  {% csrf_token %}
    

  <div class="container top-50 w-75 form-modif ">
      <div class="">
        <label class="lead m-3" for="id_login">Username:</label>
        {{form.errors.username}}
        {{form.username}}
      </div>

     <div class="">
        <label class="lead m-3" for="id_password">Password:</label>
        {{form.errors.new_password}}
        {{form.new_password}}
    </div>

     <div class="form-container remember">
        <label class="lead my-3" for="id_remember">Remember Me:</label>
        {{form.errors.remember}}
        {{form.remember}}
    </div>
  </div>
    

  <div class=" top-100 pb-5 container d-flex align-items-center justify-content-center ">

    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <button class="mx-3 mx-lg-4 btn btn-primary primaryAction" type="submit">{% trans "Sign In" %}</button>
    <a class="mx-3 mx-lg-4 btn btn-outline-warning  secondaryAction" href="">{% trans "Forgot Password?" %}</a>
  </div>
  </form>

</div>

</div>
{% endblock %}

authapp/templates/authapp/logout.html
{% extends "authapp/base.html" %}

{% load i18n %}

{% block content %}
<div class="container p-5">
  <div class="container w-auto w-lg-75 bg-dark shadow shadow-lg rounded ">

    <h1 >{% trans "Sign Out" %}</h1>

    <div class="container">
        
      <h1 class=" pt-5 text-light fw-bold fs-3 text-center ">{% trans "Sign Out" %}</h1>
      
      <p class=" text-light fw-bold fs-3 text-center ">{% trans 'Are you sure you want to sign out?' %}</p>
      
      <form class="text-center pb-5" method="POST" action="">
        {% csrf_token %}
        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
        {% endif %}
        <a class="btn btn-outline-info mx-4" href="{% url 'mypost:home' %}">Annuler</a>
        <button class="btn btn-warning mx-4" type="submit">{% trans 'Sign Out' %}</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

authapp/templates/authapp/messages.html
{% if messages %}
    <div class="text-light lead">
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
{% endif %}

authapp/templates/authapp/signup.html
{% extends "authapp/base.html" %}
{% load i18n %}

{% block content %}

<div class="container p-5">
<div class="container w-auto w-lg-75 bg-dark shadow shadow-lg rounded ">

<h1 class=" pt-5 text-light fw-bold fs-3 text-center ">{% trans "Sign Up" %}</h1>

<div class="text-light">
  {% include 'authapp/messages.html' %}
  <p class="i-account text-center">Already have an account? Then please <a class = "text-light lead mx-2" href="{% url 'authapp:account_login' %}">sign in</a></p>
</div>

<form class="signup text-light" id="signup_form" method="post" action="">
  {% csrf_token %}

  <div class="container w-75 form-modif">

    <div class="lead m-3">
      <label for="id_username">Username:</label>
      {{form.errors.username}}
      {{form.username}}
    </div>

    <div class="lead m-3">
      <label for="id_email">E-mail:</label>
      {{form.errors.email}}
      {{form.email}}
    </div>


    <div class="lead m-3">
      <label for="id_password1">Password:</label>
      {{form.errors.new_password}}
      {{form.new_password}}
    </div>

    <div class="lead m-3">
      <label for="id_password2">Confirm password:</label>
      {{form.errors.confirm_password}}
      {{form.confirm_password}}
    </div>

  </div>
    
  <div class="top-100 pb-5 container d-flex align-items-center justify-content-center">
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
    {% endif %}
    <button class="mx-3 mx-lg-4 btn btn-primary" type="submit">{% trans "Sign Up" %}</button>
  </div>

</form>

</div>
</div>
{% endblock %}

authapp/templates/authapp/snippet.html
{% load i18n %}

<div
  class="modal fade rounded"
  id="exampleModal"
  tabindex="-1"
  aria-labelledby="exampleModalLabel"
  aria-hidden="true"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div
        class="
          container
          text-light
          w-auto w-lg-75
          bg-dark
          shadow shadow-lg
          rounded
        "
      >
        <div class="modal-header">
          <h5 class="m-auto" id="exampleModalLabel">{% trans "Sign Out" %}</h5>
        </div>
        <div class="modal-body">
          <div class="container">
            <p class="fs-2 text-center lead">
              {% trans 'Are you sure you want to sign out?' %}
            </p>

            <form
              class="text-center"
              method="POST"
              action="{% url 'authapp:account_logout' %}"
            >
              {% csrf_token %} {% if redirect_field_value %}
              <input
                type="hidden"
                name="{{ redirect_field_name }}"
                value="{{ redirect_field_value }}"
              />
              {% endif %}

              <div
                class="
                  modal-footer
                  d-flex
                  justify-content-center
                  align-items-center
                  text-center
                "
              >

                <button
                  type="button"
                  class="btn btn-info px-2 mx-3"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                >Annuler</button>

                <!-- <a
                  class="btn btn-outline-info px-2 mx-3"
                  href="{% url 'mypost:home' %}"
                  >Annuler</a
                > -->

                <button class="btn btn-outline-warning px-2 mx-3" type="submit">
                  {% trans 'Sign Out' %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>