authapp/urls.py
from django.urls import path

from django.urls import path

from authapp import views


app_name = "authapp"
urlpatterns = [
    path('signup/', views.signup, name= 'account_signup'),
    path("login/", views.loginUser, name="account_login"),
    path("logout/", views.logoutUser, name="account_logout"),
   	path('changepassword/', views.PasswordChange, name='change_password'),
   	path('changepassword/done', views.PasswordChangeDone, name='change_password_done'),

]

mypost/urls.py
from django.urls import path

from . import views

from .views import (
    SearchView,
    CommentListView,
    HomeView,
    CreatePostView,
    PostListView,
    PostUpdateView,
    PostDetailView,
    PostDeleteView,
)

app_name = 'mypost'
urlpatterns = [
    path('', HomeView.as_view(), name ='home'),
    path('post-create/', CreatePostView.as_view(), name='post_create'),
    path('post-list/', PostListView.as_view(), name='post_list'),
    path('post-update/<int:pk>/',PostUpdateView.as_view(), name='post_update' ),
    path('post-detail/<int:pk>/', PostDetailView.as_view(), name ='post_detail'),
    path('post-delete/<int:pk>/', PostDeleteView.as_view(), name ='post_delete'),

    # path('post-detail/<int:pk>/comment/', CommentView.as_view(), name='comment_post' ),
    path('post-detail/<int:pk>/comment-list/', CommentListView.as_view(), name='comment_post' ),
    path('search/', SearchView.as_view(), name='search_post' ),
    
    # path('search/', views.search, name='search_post'),


    
]

post/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authapp.urls')),
    path('', include('mypost.urls')),
    path('profile/', include('profilapp.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

profilapp/urls.py
from django.urls import path

from profilapp.views import (
    profil,
    # ProfileCreateView,
    ProfileUpdateView,
    ProfileDetailView,
)


app_name = 'profilapp'
urlpatterns = [
    # path('create/', ProfileCreateView.as_view(), name='create_profile'),
    
    path('update/<pk>/', ProfileUpdateView.as_view(), name='update_profile'),
    path('<pk>/', ProfileDetailView.as_view(), name="profile"),
    
]

mypost/models.py
from django.db import models
from django.urls import reverse

from utils.models import UrlMixin, TimeStampedModel
from post import settings

# Create your models here.
User = settings.AUTH_USER_MODEL


class PostView(models.Model):
    post_view = models.ForeignKey('Post', on_delete=models.CASCADE)
    view_user = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(TimeStampedModel):
    for_post = models.ForeignKey('Post', related_name='comments', on_delete=models.CASCADE)
    comment_by = models.ForeignKey(User, verbose_name="Commenter par", on_delete=models.CASCADE)
    comment_body = models.TextField(verbose_name="Votre commentaire")

    class Meta:
        ordering = ["-created"]
        verbose_name_plural = "Comments"

    def __str__(self):
        return self.comment_by.username


class Post(TimeStampedModel):
    post_by = models.ForeignKey(User, verbose_name="Auteur", on_delete=models.CASCADE)
    title = models.CharField(max_length=60, verbose_name="Titre")
    overwiew = models.CharField(max_length=20, verbose_name="Bref appercu du post", )
    key_words = models.CharField(max_length=20, verbose_name='Mots clés...  Facultatif', null=True, blank='True')
    content = models.TextField(verbose_name="Contenu du post")
    post_image = models.ImageField(upload_to="media", verbose_name="Associer une image")
    previous_post = models.ForeignKey('self', related_name='previous', null=True, blank=True, on_delete=models.SET_NULL)
    next_post = models.ForeignKey('self', related_name='next', null=True, blank=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ["-created"]
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('mypost:post_detail', kwargs={
            'pk': self.pk
        })

    def get_update_url(self):
        return reverse('mypost:post_update', kwargs={
            'pk': self.pk
        })

    def get_delete_url(self):
        return reverse('mypost:post_delete', kwargs={
            'pk': self.pk
        })

    def get_comment_url(self):
        return reverse('mypost:comment_post', kwargs={
            'pk': self.pk
        })

    @property
    def view_count(self):
        return PostView.objects.filter(post_view=self).count()

    @property
    def comment_count(self):
        return Comment.objects.filter(for_post=self).count()

    @property
    def get_comments(self):
        return self.comments.all().order_by('-created')

mypost/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(
        label = "Contenu du post",
        widget=forms.Textarea(
            attrs={'required': True,
                 'cols': 30, 'rows': 10,
                 'class': 'form-control'}
        )
    )

    title = forms.CharField(
        label = "Titre",
        widget = forms.TextInput(
            attrs = {
                'required': True,
                'cols': 30, 'row':2,
                'class':'form-control',
            }
        )
    )

    overwiew = forms.CharField(
        label = "Bref appercu du post",
        widget = forms.TextInput(
            attrs = {
                'required': True,
                'cols': 30, 'row':20,
                'class':'form-control',
            }
        )
    )

    key_words = forms.CharField(
        label = "Mots clés...  Facultatif",
        required=False,
        widget = forms.TextInput(
            attrs = {
                'cols': 30, 'row':2,
                'class':'form-control',
            }
        )
    )



    class Meta:
        model = Post
        fields = ('title','overwiew','key_words', 'content', 'post_image','previous_post', 'next_post' )


class CommentForm(forms.ModelForm):
    email = forms.EmailField(
                    required = False,
                    widget = forms.TextInput(
                        attrs = {
                            'class': 'form-control',
                            'placeholder':"Your E-mail... not required!"
                        }
                    )
    )

    comment_body = forms.CharField(
                    widget = forms.Textarea(
                        attrs = {
                            'class': 'form-control',
                            'rows':"10", 'cols':"50",
                        }
                    )
    )
    class Meta:
        model =  Comment
        fields = ('comment_body',)

mypost/views.py
from django.db.models import Count, Q
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator

from profilapp.models import Profile

from mypost.models import Post, PostView, Comment
from mypost.forms import PostForm, CommentForm
from mypost.decorator import un_authenticated_user

# from profilapp.models import ReaderProfil, AuthorProfil

from django.conf import settings
from django.contrib.auth.decorators import login_required


def my_view(request):
    if not request.user.is_authenticated:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))


#

# def search(request):
#     if not request.user.is_authenticated:
#         return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

#     else:
#         queryset = Post.objects.all()
#         query = request.GET.get('q')
#         if query:
#             queryset = queryset.filter(
#                 Q(title__icontains=query) |
#                 Q(overwiew__icontains=query)
#             ).distinct()
#     context = {
#         'queryset': queryset
#     }
#     return render(request, 'mypost/search_result.html', context)

# @login_required
# def search(request):
#     queryset = Post.objects.all()
#     query = request.GET.get('q')
#     if query:
#         queryset = queryset.filter(
#             Q(title__icontains=query) |
#             Q(overwiew__icontains=query)
#         ).distinct()
#     context = {
#         'queryset': queryset
#     }
#     return render(request, 'mypost/search_result.html', context)


class SearchView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        queryset = Post.objects.all()
        query = request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) |
                Q(overwiew__icontains=query) |
                Q(key_words__icontains=query)
            ).distinct()

        context = {
            'queryset': queryset,
            'query': query,
        }
        return render(request, 'mypost/search_result.html', context)


class HomeView(TemplateView):
    template_name = 'mypost/home.html'

    def get_context_data(self, **kwargs):
        post = Post.objects.all()
        context = super().get_context_data(**kwargs)

        context["post"] = post
        return context


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'mypost/create-post.html'
    context_object_name = "post"
    form_class = PostForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Create'
        return context

    def form_valid(self, form):
        form.instance.post_by = self.request.user
        form.save()
        return redirect(reverse("mypost:post_detail", kwargs={
            'pk': form.instance.pk
        }))


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    context_object_name = "post"
    template_name = 'mypost/create-post.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.post_by = self.request.user
        form.save()
        return redirect(reverse('mypost:post_detail', kwargs={
            'pk': form.instance.pk
        }))


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    context_object_name = "post"
    success_url = reverse_lazy('mypost:home')
    template_name = 'mypost/detail.html'

    def get_object(self):
        obj = super().get_object()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        context["post_by"] = post.post_by.username
        return context


class PostListView(ListView):
    model = Post
    context_object_name = 'post_list'
    template_name = "mypost/post_list.html"
    paginate_by = 6


class PostDetailView(DetailView):
    model = Post
    template_name = 'mypost/detail.html'
    context_object_name = 'post'
    form = CommentForm()

    @method_decorator(un_authenticated_user)
    def dispatch(self, * args, ** kwargs):
        return super().dispatch( * args, ** kwargs)

    def get_object(self):
        obj = super().get_object()
        self.request.session['last_view'] = obj.id
        try:
            PostView.objects.get_or_create(
                view_user=self.request.user,
                post_view=obj
            )
            
        except:
            pass
        return obj

    def get_context_data(self, **kwargs):
        most_recent = Post.objects.all().order_by('-created')[:4]
        context = super().get_context_data(**kwargs)
        context['most_recent'] = most_recent
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        form = CommentForm(request.POST)
        post = self.get_object()
        if form.is_valid():
            form.instance.comment_by = request.user
            form.instance.for_post = post
            form.save()
        return redirect(reverse("mypost:post_detail", kwargs={
            'pk': post.pk
        }))


class CommentListView(View):
    model = Comment
    template_name = "mypost/detail.html"
    login_url = '/../../../account/login/'
    # redirect_field_name = 'next'
    context_object_name = "comment_list"

    def get_object(self):
        obj = super().get_object()
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_comment"] = self.get_object()
        return context

mypost/templates/mypost/_comments.html
<section>
  <div class="container">
    <div class="accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingOne">
          <button
            class="accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#flush-collapseOne"
            aria-expanded="false"
            aria-controls="flush-collapseOne"
          >
            Laisser un commentaire
          </button>
        </h2>
        <!-- </div> -->

        <div
          id="flush-collapseOne"
          class="accordion-collapse collapse"
          aria-labelledby="flush-headingOne"
          data-bs-parent="#accordionFlushExample"
        >
        {% if request.user.is_authenticated %}
          <section class="accordion-body">
            <form action="" method="POST" class="container-fluid">
              {% csrf_token %}
              <div class="input-group pt-3">
                <span class="input-group-text" id="basic-addon1">@</span>
                {{form.email}}
              </div>

              <div class="myForm pt-3">
                <p>
                  [&nbsp;<span
                    class="intLink p-2"
                    onclick="insertMetachars('&lt;strong&gt;','&lt;\/strong&gt;');"
                    ><strong>Bold</strong></span
                  >
                  |
                  <span
                    class="intLink"
                    onclick="insertMetachars('&lt;em&gt;','&lt;\/em&gt;');"
                    ><em>Italic</em></span
                  >
                  |
                  <span
                    class="intLink"
                    onclick="var newURL=prompt('Enter the full URL for the link');if(newURL){insertMetachars('&lt;a href=\u0022'+newURL+'\u0022&gt;','&lt;\/a&gt;');}else{document.myForm.myTxtArea.focus();}"
                    >URL</span
                  >
                  |
                  <span
                    class="intLink"
                    onclick="insertMetachars('\n&lt;code&gt;\n','\n&lt;\/code&gt;\n');"
                    >code</span
                  >
                  |
                  <span class="intLink" onclick="insertMetachars(' :-)');"
                    >smile</span
                  >
                </p>
                {{form.comment_body}} <input class="btn btn-outline-warning pt-2
                mt-4" type="submit" value="Send"
              </div>
            </form>
          </section>

          {% else %}
          <div class="container">
            <p class="lead text-center m-3">
              Connecter vous pour pouvoir commenter ce post!
            </p>
            <a class="btn btn-primary mb-3" href="#">Se connecter</a>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

    

<h1></h1>
<section class="">
    <div class="container">
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="flush-headingTwo">
          <button
            class="bg-dark text-light h2 accordion-button collapsed"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#flush-collapseTwo"
            aria-expanded="false"
            aria-controls="flush-collapseTwo"
          >
            Voir les commentaires de ce post
          </button>

        </h2>

        <div
          id="flush-collapseTwo"
          class="accordion-collapse collapse"
          aria-labelledby="flush-headingTwo"
          data-bs-parent="#accordionFlushExample"
          >
          <div class="accordion-body ">

            
            {% for comment in post.get_comments  %}
            <div class=" d-flex comment_title align-items-sm-baseline justify-content-md-start justify-content-center">
                <img class="d-inline" src="{{comment.comment_by.profile.url}}" alt="">
                <h5 class="d-inline px-2">{{comment.comment_by.username}} <span class="px-3">E-mail: {{comment.email}}</span></h5>
                <p class="d-inline px-4">depuis {{comment.created | timesince}}</p>
            </div>
            <div class=" border border-dark px-2 px-md-4">
              <p class="w-auto"><span class=" lead text-wrap ">{{comment.comment_body}}</span></p>
            </div>
            {% endfor %}
            
            
            {% comment %}
                
            
            
            {% else %}
            <div class="container">
              <p class="lead m-3 text-center">
                Connecter vous pouvoir lire les commentaires
              </p>
              <form action="" method="GET">
                <input name="" type="hidden">
                
                <!-- <a class=" mb-3"  href="{% url 'authapp:account_login' %}" >
                    se connecter
                </a> -->
                {% endif %}
                
                
            </div>
            {% endcomment %}
            
        
        </div>
    </div>
    </div>
  </div>
</section>

mypost/templates/mypost/_footer.html
    <footer class="p-3 p-lg-5   bg-dark text-center text-light position-relative">
      <div class="container d-none d-md-block">
        <div class="row justify-content-between ">
          <div class=" col col-md-6 col-lg-3 lead">
            <h3 class="pb-1">Contact</h3>
            <a class="d-block text-light text-decoration-none" href="tel:+49.157.0156">+49 157 0156</a>
            <a class="d-block text-light text-decoration-none" href="mailto:exemple@exemple.com">Send email to nowhere</a>
            <a class="d-block text-light text-decoration-none" href="https://www.exemple.com">exemple </a>
          </div>

          <div class="col col-md-6 col-lg-3 lead">
            <h3>Liens Importants</h3>
            <div class="mt-4">
              <a class="d-block text-light text-decoration-none" href="{% url 'mypost:post_list' %}">Blog</a>
              <a class="d-block text-light text-decoration-none" href="#">Politique de confidentialité</a>
              <a class="d-block text-light text-decoration-none" href="#">Voir son compte</a>
            </div>
          </div>
        </div>
      </div>

      <div class="container mt-4">
        <p class="lead">Copyright &copy {% now 'y' %} Padawans.io</p>
      </div>
    </footer>

mypost/templates/mypost/_head.html
{% load static %}
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link
    rel="stylesheet"
    href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
  />

  <link
    rel="stylesheet"
    href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}"
  />

  <link
    rel="stylesheet"
    href="{% static 'bootstrap/dist/css/mdb.min.css' %}"
  />

  <link
    rel="stylesheet"
    href="{% static 'bootstrap/dist/css/style.min.css' %}"
  />

  <link rel="stylesheet" href="{% static 'mypost/css/base.css' %}" />


  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
  <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>


  <title>{% block title %} post {% endblock title %}</title>
</head>

mypost/templates/mypost/_navbar.html
<nav class="p-3 navbar navbar-expand-lg bg-dark navbar-dark fixed-top">
  <div class="container-fluid">
    <a href="{% url 'mypost:home' %}" class="navbar-brand mx-5">Padawans</a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navmenu"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse text-lg-center" id="navmenu">
      <ul class="fs-5 navbar-nav me-auto">
        <li class="nav-item">
          <a href="{% url 'mypost:post_list' %}" class="nav-link text-capitalize">blog</a>
        </li>

        
        {% if request.user.is_authenticated %}

        {% comment %}
          
        {% endcomment %}
        <li class="nav-item">
          {% if request.user.profile.id %}
          <a href="{% url 'profilapp:profile' request.user.profile.id %}" class="nav-link text-capitalize">Profil</a>
          {% endif %}
        </li>
          
        <li class="nav-item">
          <a
            data-bs-toggle="modal" 
            data-bs-target="#exampleModal" 
            href="{% url 'authapp:account_logout' %}" 
            class="nav-link text-capitalize">logout</a>
        </li>

<!-- 
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              ...
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
      </div> -->

        {% else %}
        
        <li class="nav-item">
          <a href="{% url 'authapp:account_login' %}" class="nav-link text-capitalize">login</a>
        </li>
          
        {% endif %}
          
        <li class="nav-item">
          <a href="#" class="nav-link text-capitalize">contact</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link text-capitalize">a propos</a>
        </li>
        
      </ul>

      <form action="{% url 'mypost:search_post'%}" method="GET" class="d-flex">
        <input
          name = 'q'
          class="form-control me-2"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-outline-warning" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

mypost/templates/mypost/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% include 'mypost/_head.html' %}
 <body class="body">
     
     {% include 'mypost/_navbar.html' %}

     {% include 'authapp/snippet.html' %}

     {% block body %}
     
     {% comment %}
    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
    {% endcomment %}
    
      {% block content %}
      
      {% endblock %}

    {% endblock %}

    {% block extra_body %}
    {% endblock %}
    {% include 'mypost/_footer.html' %}

    
    {% block script %}
      
    {% endblock script %}

  </body>
</html>

mypost/templates/mypost/create-post.html
{% extends 'mypost/base.html' %} {% block content %}

<div class="">
  <div class="container w-75 form-modif">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <label for="id_title" class="lead m-3">Titre</label>
      {{form.errors.title}} {{form.title}}

      <label for="id_overwiew" class="lead m-3">Bref appercu du post</label>
      {{form.errors.overwiew}} {{form.overwiew}}

      <label for="id_key_words" class="lead m-3"
        >Mots clés... <span class="px-3">Facultatif</span>
      </label>
      {{form.errors.key_words}} {{form.key_words}}

      <label for="id_content" class="lead m-3">Contenu du post</label>
      {{form.errors.content}} {{form.content}}

      <div class="d-block">
        <label for="id_post_image" class="lead m-3">Associer une image</label>
        {{form.errors.post_image}} {{form.post_image}}
      </div>

      <div class="d-block">
        <label for="id_post_image" class="lead m-3">Lier a un post (Previous post)</label>
        {{form.errors.previous_post}} {{form.previous_post}}
      </div>

      <div class="d-block">
        <label for="id_post_image" class="lead m-3">Lier a un post (next post)</label>
        {{form.errors.next_post}} {{form.next_post}}
      </div>
      
      
      <button class="btn btn-info mt-4" type="submit">Créer le post</button>
    </form>
  </div>
</div>

{% endblock content %}

mypost/templates/mypost/detail.html
{% extends 'mypost/base.html' %} {% block content %}

<main class="col">
  <div class="img_full">
    <img class="shadow detail-img" src="{{post.post_image.url}}" alt="" />
  </div>
  <div class="container-fluid text-center">
    <h1
      class="
        lead
        w-75
        fs-2
        text-light text-center
        position-absolute
        top-50
        post-title
      "
    >
      {{post.title}}
    </h1>
  </div>

  <div class="row container-fluid mx-3 mx-lg-0 p-0 p-lg-5">
    <div class="col-lg-2 px-lg-3 mb-5 mb-lg-2">
      <!-- <h4 class="text-center m-4 mb-lg-4 mt-lg-0">Saisir un mot clé</h4>
      <form class="d-flex mb-lg-3">
        <input
          class="form-control"
          type="search"
          placeholder="Search"
          aria-label="Search"
        />
        <button class="btn btn-warning" type="submit">Search</button>
      </form> -->

      
      <div class="mt-4 mt-lg-0 text-center text-lg-start">
        <a href="#partager" class="btn btn-info mb-lg-3">Partager le post</a>
        <a href="{{post.get_comment_url}}" class="btn btn-outline-warning mb-lg-3"
          >Commenter</a
        >
      </div>
      <div class="mt-4 mt-lg-0 text-center text-lg-start">
        
        <a href="{% url 'mypost:post_create' %}" class="btn btn-info mb-lg-3"
        >Create un post</a
        >
        {% if request.user.is_authenticated and user == post.post_by %}

        <a href="{{post.get_update_url}}" class="btn btn-info mb-lg-3"
          >Modifier le post</a
        >

        <!-- <a href="{{post.get_delete_url}}" class="btn btn-info mb-lg-3">Supprimer le post</a> -->
        <a
          class="btn btn-info mb-lg-3"
          data-bs-toggle="modal"
          href="#exampleModalToggle"
          role="button"
          >Supprimer le post
        </a>
        {% endif %}
      </div>
    </div>

    <!-- =============modal======= -->

    <div
      class="modal fade"
      id="exampleModalToggle"
      aria-hidden="true"
      aria-labelledby="exampleModalToggleLabel"
      tabindex="-1"
      data-bs-backdrop="static"
      data-bs-keyboard="false"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalToggleLabel">
              Suppression du post <em class="px-2"><< {{post.title}}>></em>
            </h5>

          </div>
          {% if user.is_authenticated and user != post.post_by %}
          <div class="container">
            <p>Vous devez étre l'auteur de ce post pour pouvoir le supprimer</p>
          </div>

          {% else %}
          <div class="modal-body">
            <div class="">
              <div class="container d-inline text-center">
                <a
                  type="button"
                  data-bs-dismiss="modal"
                  aria-label="Close"
                  class="d-inline btn btn-info text-dark lead mx-2"
                  >Annuler la suppression</a
                >

                <!-- <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button> -->
                <form
                  class="d-inline"
                  action="{{post.get_delete_url}}"
                  method="POST"
                  enctype="multipart/form-data"
                >
                  {% csrf_token %}
                  <button class="btn btn-danger lead" type="submit">
                    Confirmer la suppression
                  </button>
                </form>
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- ========================= -->

    <div class="row col-lg-8 lead px-4 px-lg-5">
      <p class="">{{post.content | safe}}</p>
    </div>
    <div class="row col-lg-2 my-3 my-lg-0">
      <div class="container px-5 px-lg-0">
        <h4 class="text-center mb-lg-4">Detail sur le post</h4>
        <p>
          Date de publication:
          <span class="lead fw-bold">{{post.created}}</span>
        </p>
        <p>Modifier <span class="lead fw-bold">{{post.modified}}</span></p>
        <p>
          Auteur:
          <span class="lead fw-bold text-uppercase"
            ><a href="{% url 'profilapp:profile' post.post_by.profile.id %}">@{{post.post_by.profile.first_name}}</a>
          </span>

        <p>
          <a class="lead text-capitalize" href="{% url 'profilapp:profile' post.post_by.profile.id %}">Voir le profil</a>
        </p>
        </p>
        <p><span class="lead fw-bold">{{post.view_count}}</span> lectures</p>
        <p>
          <span class="lead fw-bold">{{post.comment_count}}</span> commentaires
        </p>
        

      </div>
    </div>
  </div>
</main>

<section class="container">
<h3 class="text-center lead text-capitalize">Post recents</h3>

{% for recent_post in most_recent %}
  
  {% if post.id != recent_post.id %}
  <div class="container mb-5  ">
    <a class="text-decoration-underline" href="{{recent_post.get_absolute_url}}">{{recent_post.title}}</a>
    <p class="card-text">{{recent_post.content | truncatewords:"16"}}</p>
    <p class="lead text-capitalize">by {{recent_post.post_by}} <span>le {{recent_post.created}}</span></p>
  </div>

  {% endif %}
    
{% endfor %}
  
</section>


{% include 'mypost/_comments.html' %}

{% endblock content %}

mypost/templates/mypost/post_confirm_delete.html
{% extends 'mypost/base.html' %} {% block content %}

<!-- {{author}} -->
<div class="col form-modif-delete">
  <div class="container mt-5 d-block text-center delete">
    <a href="{{post.get_absolute_url}}" class="btn btn-info text-dark"
      >Annuler la suppression</a
    >
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <button class="btn btn-danger" type="submit">
        Confirmer la suppression
      </button>
    </form>
  </div>
</div>

{% endblock content %}